version: '3'

services:
  nats:
    image: nats:2.7-alpine
    volumes:
    - ./nats.conf:/nats.conf
    command: ["--config", "/nats.conf"]
  nats-exporter:
    image: bitnami/nats-exporter
    command: ["-varz", "http://nats:8222"]
    depends_on:
    - nats
  sockroom:
    build: .
    volumes:
    - ./config.docker.toml:/config.toml
    ports:
    - 8080:80
    depends_on:
    - nats
  prometheus:
    image: bitnami/prometheus:2
    volumes:
    - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
    - 9090:9090
