global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files: []

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
- job_name: nats
  static_configs:
  - targets: ['nats-exporter:7777']
- job_name: sockroom
  static_configs:
  - targets: ['sockroom:80']
